version: '3.4'
services:
  dhs-update:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/dplus-hs-update/firestore
    environment:
      - FIRESTORE_EMULATOR_HOST='localhost:8080'
      - GCLOUD_PROJECT='dplus-hotstar-th'
      - DISCORD_WEBHOOK_ID=''
      - DISCORD_WEBHOOK_TOKEN=''
