version: '3.4'
services:
  dhs-update:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISCORD_WEBHOOK_ID='${DISCORD_WEBHOOK_ID}'
      - DISCORD_WEBHOOK_TOKEN='${DISCORD_WEBHOOK_TOKEN}'
      - DATABASE_URL='${DATABASE_URL}'
